version: "3"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "dfsdb"
      MYSQL_USER: "dfsuser"
      MYSQL_PASSWORD: "DFSpassword_123"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_dir
    environment:
      AWS_ACCESS_KEY_ID: "AKIASZASMGKR2Z7CN35L"
      AWS_SECRET_ACCESS_KEY: "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"
      AWS_STORAGE_BUCKET_NAME: "dataset-s3-bucket"
    ports:
      - "8000:8000"
    depends_on:
      - db
